apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendgrid-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sendgrid-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: sendgrid-exporter
    spec:
      containers:
      - name: sendgrid-exporter
        image: ustiuzhanin/sendgrid-statistics-exporter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 18080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0:18080"
        - name: METRICS_ENDPOINT
          value: "/metrics"
        - name: SENDGRID_API_KEY
          valueFrom:
            configMapKeyRef:
              name: sendgrid-exporter
              key: sendgrid.api_key
---
apiVersion: v1
kind: Service
metadata:
  name: sendgrid-exporter
spec:
  clusterIP: None
  selector:
    name: sendgrid-exporter
  ports:
  - name: sendgrid-exporter
    protocol: TCP
    port: 18080
    targetPort: 18080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sendgrid-exporter
data:
  sendgrid.api_key: ""
